name: OreGenerator for Nukkit
main: me.pkt77.oregenerator.OreGenerator
version: 2.0
author: pkt77, NycuRO

commands:
    og:
        description: Shows list of commands.

permissions:
    og.reload:
        description: Reloads the config file.
        default: false
